apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kafka-storage-class
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
