---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  finalizers:
  - kafkatopic.finalizers.platform.confluent.io
  name: mrc-topic
  namespace: qyang
spec:
  partitionCount: 1
  configs:
    "cleanup.policy": "delete"
    "confluent.placement.constraints": "{ \"version\": 2, \"replicas\": [ {\r\n            \"count\": 2,\r\n            \"constraints\": {\r\n                \"rack\": \"us-east-1b\"\r\n            }\r\n        },\r\n        {\r\n          \"count\": 1,\r\n          \"constraints\": {\r\n              \"rack\": \"us-east-1c\"\r\n          }\r\n      }\r\n    ],\r\n    \"observerPromotionPolicy\":\"under-min-isr\"\r\n}"
  kafkaClusterRef:
    name: kafka
    namespace: qyang
  kafkaRestClassRef:
    name: kafka-rest
    namespace: qyang
---

apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  finalizers:
  - kafkatopic.finalizers.platform.confluent.io
  name: pageviews
  namespace: qyang
spec:
  partitionCount: 1
  kafkaRestClassRef:
    name: kafka-rest
    namespace: qyang
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  finalizers:
  - kafkatopic.finalizers.platform.confluent.io
  name: orders
  namespace: qyang
spec:
  partitionCount: 1
  kafkaRestClassRef:
    name: kafka-rest
    namespace: qyang

